# From: https://github.com/argenos/nldates-obsidian/blob/master/.github/workflows/release.yml
name: Release obsidian plugin

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' # Push events to matching any tag format, i.e. 1.0, 20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run test --if-present
          npm run build --if-present
          npx rexreplace "^.*?#(#+\s\[.*?\n.*?)(?=\s*#+\s\[)" "_" -s -M -G -m -o "CHANGELOG.md" > CHANGELOG-LATEST.md

      - name: Get tag
        id: tag
        run: |
          echo "tag="${GITHUB_REF#refs/tags/}"" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=${{ steps.tag.output.tag }}
          gh release create "$tag"  \
            --title="$tag" \
            main.js manifest.json styles.css
        with:
          tag_name: ${{ steps.tag.output.tag }}
          release_name: ${{ steps.tag.output.tag }}
          body_path: CHANGELOG-LATEST.md
          draft: false
          prerelease: false
