name: Test Linked Data Helper

on:
  push:
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # You might need to adjust this value to your own version
      - name: npm install
        id: npm-install
        run: |
          npm install
      - name: Test
        id: test
        run: |
          npm run test
